### ISSUE TITLE
ProductInventoryDAO 성능최적화

### ISSUE THREAD

**Issue by Dubutoto** [Dubutoto/LogisticsControl#74]
ProductInventoryDAO 내부 메소드, 물품 재고 조회 탐색속도를 최적화 합니다.

고려 해볼만한 성능향상점은 두가지입니다.

1. Query 최적화 : MYSQL 내부 INDEX 를 도입해 검색속도를 벤치마킹해 효율성을 테스트합니다.

2. 코드 Refactoring: 탐색하는 코드에 자료구조 ex(트리, 우선순위큐) 를 도입하여 효율성을 테스트합니담

**Comment by newbackjava** [comment]
- Query 최적화 : MYSQL 내부 INDEX 를 도입해 검색속도를 벤치마킹해 효율성을 테스트합니다.
==> 기본키를 통해 이미 클러스터드 인덱스가 설정되었고
==> 검색도 pk인 id로 하게 되기 때문에 별도의 인덱스를 추가로 지정하지 않는 것이 좋을 듯.

==> pk가 아닌 다른 항목으로 검색이 이루어지는 경우 세컨드리 인덱스를 만들어 추가하여 성능을 개선할 수는 있으나
        이번 프로젝트 프로세스에서는 pk중심의 검색위주로 진행되어 
       세컨드리 인덱스가 불필요해보임.
      
==> 다른 팀원들도 의견있으시면 여기에 comment를 작성해주세요.!!!

**Comment by newbackjava** [comment]
**코드 리펙트링**
==> 다른 객체를 사용하여 성능을 개선할 수는 있으나
        메서드나 클래스 단위로 분리시킬 작업이 있는지 확인하여
        만약 분리가 되어있지 않으면 
        분리하는 작업의 리펙토링을 하면 좋겠음.

**Comment by Dubutoto** [comment]
의견 감사합니다 참고하겠습니다
