### ISSUE TITLE
Main 클래스 생성 및 메소드 통합

### ISSUE THREAD

**Issue by Dubutoto** [Dubutoto/LogisticsControl#75]
Main 클래스를 생성하고 메소드를 통합한후 CLI내에서 모든 기능이 정상적으로 작동하는지 확인합니다

**Comment by newbackjava** [comment]
**인터페이스 추출시**

- 몇 개의 메서드가 의도대로 작성되지 않으신 분들은
<b>개인적으로 질문</b> 부탁드립니다.!!!
