### ISSUE TITLE
PPT 제작

### ISSUE THREAD

**Issue by Dubutoto** [Dubutoto/LogisticsControl#78]
Presentation 용 ppt 를 제작해야합니다

**Comment by newbackjava** [comment]
ppt작성은 제가 드렸던 ppt문서 참고해서 
그 안에 있는 것은 다 넣고
추가로 진행했던 부분은 화면캡쳐하여
첨부하시면 될 듯!!

**Comment by Dubutoto** [comment]
감사합니다 참고하겠습니다

**Comment by Dubutoto** [comment]
감사합니다 참고하겠습니다

**Comment by newbackjava** [comment]
이슈 오른쪽의 라벨은 여러개 설정가능합니다.
