### ISSUE TITLE
창고 관리 시스템

### ISSUE THREAD

**Issue by 0O000** [Dubutoto/LogisticsControl#80]
### 1. 창고 관리
- [x] 창고 생성 기능 구현
- [x] 창고 리스트 확인 기능 구현
- [x] 창고 수정 기능 구현
- [x] 창고 삭제 기능 구현

### 2. 창고 재고 리스트
- [x] 상품 ID, 상품 이름, 가격, 수량, 업데이트 날짜 확인 기능 구현
    - [x] 창고ID가 없을 경우 예외처리
- [ ] 재고 조회 성능 최적화

### 3. 창고 공급 요청
- [x] 공급 요청 후 창고 재고 변화
- [x] 공급 요청 내역 기록 기능 추가
- [x] 창고 용량 넘을 경우 예외처리

### 4. 주문 신청
- [x] 창고ID, 지점ID가 없을 경우 예외처리
- [x] 창고ID, 지점ID, 상품ID, 요청수량을 입력시 주문 가능

### 5. 주문내역 관리
- [x] 주문별 창고, 지점, 상태, 상품, 수량, 주문 날짜 정보 확인 기능 구현
    - [x] 주문별 총 금액 확인
- [x] 트랜잭션을 이용한 주문 승인(commit) 및 거절(rollback)
    - [x] 주문ID 없을 경우 예외처리
    - [ ] 창고 부족시 거절 예외처리
- [ ] 거절된 주문에 대한 재주문 요청 기능 구현
- [x] 주문 상태 변경 구현

**Comment by newbackjava** [comment]
체크리스트 좋네요!! 한눈에 기능별로 정리가 됩니다.!!!

**Comment by 0O000** [comment]
네 감사합니다!
