### ISSUE TITLE
[PR] 이슈 템플릿 동기화

### ISSUE THREAD

**Issue by Dubutoto** [Dubutoto/LogisticsControl#93]
## 📢 변경 사항
- 이슈 템플릿을 Main 브랜치에서 develop 브랜치로 PR 합니다.

## ✨ 주요 변경 내용
- 버그 리포트 이슈 템플릿 추가
- PR    리포트 이슈 템플릿 추가

## ✅ 체크리스트
- [x] 코드가 정상적으로 동작하는지 확인했습니다.
- [ ] 모든 변경 사항에 대해 테스트를 추가했습니다.
- [x] 변경 사항과 관련된 문서를 업데이트했습니다.
- [ ] 코드 리뷰 피드백을 반영했습니다. (PR 업데이트 시)

## 🛠️ 테스트 방법
- 새로운 이슈를 템플릿을 이용해 작성 해보시길 권장합니다.

## 📸 스크린샷 (옵션)
- 관련된 UI 변경 사항이 있다면 스크린샷을 첨부해주세요.
  - 예: 
    ![스크린샷](https://via.placeholder.com/800x600)

## ⚠️ 참고 사항
-

**Comment by newbackjava** [comment]
다른 분들도 이 템플릿으로 이슈작성해보시길!!! 
작성시 오른쪽 이슈 옵션도 사용해보세요.!!

:smile project까지 만들어두셨으니 싱크시켜보시면 좋을 듯!

**Comment by 0O000** [comment]
굳굳
